schema-version = 1
id = "benchmark"
name = "wsh benchmark"
left = ["cwd", "git", "prompt-character"]
right = []

[context]
enabled = false
show-local = false
show-ssh = false
prefix = ""
separator = "@"
suffix = " "
color = "default"

[cwd]
enabled = true
style = "short"
show-on-change = false
max-length = 80
home-symbol = "~"
color = "default"

[git]
enabled = true
compact = false
hide-branches = []
prefix = " ZTB_GIT["
separator = ":"
color = "default"

[git.symbols]
branch = ""
detached = "ZTB_COMMIT@"
tag = "ZTB_TAG@"
clean = "clean"
staged = "staged"
modified = "unstaged"
untracked = "untracked"
ahead = "ahead"
behind = "behind"
diverged = "diverged"
rebase = "rebase"
merge = "merge"
cherry-pick = "cherry-pick"
revert = "revert"
bisect = "bisect"

[duration]
enabled = false
threshold-ms = 2000
format = "milliseconds"
prefix = "took "
suffix = " "
color = "default"

[prompt-character]
enabled = true
success = "]ZTB_PROMPT>"
failure = "]ZTB_PROMPT>"
privileged = "]ZTB_PROMPT>"
success-color = "default"
failure-color = "default"
privileged-color = "default"
